import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Barlow as Font } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";

import "./globals.css";

const font = Font({
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} bg-background text-foreground selection:bg-zinc-600`}
      >
        <ThemeProvider attribute="class">{children}</ThemeProvider>

        <Toaster />
      </body>
    </html>
  );
}
